// <auto-generated />
using LendingPlatform.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LendingPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(LendingDbContext))]
    [Migration("20260918110511_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("LendingPlatform.Domain.Entities.LoanApplication", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CreditScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Decision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DecisionReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LoanAmount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ltv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RulesJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("RulesJson");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Decision");

                    b.ToTable("LoanApplications", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
